// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Ordered")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookCategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Thomas Cormen",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 100f,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert Martin",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 120f,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Andrew Hunt",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 90f,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Fowler",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 150f,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eric Evans",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 80f,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Steve McConnell",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 110f,
                            Title = "Code Complete"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Kent Beck",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 95f,
                            Title = "Test Driven Development"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Donald Knuth",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 140f,
                            Title = "The Art of Computer Programming"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Jon Skeet",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 70f,
                            Title = "C# In Depth"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Al Sweigart",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 85f,
                            Title = "Automate the Boring Stuff with Python"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Gayle Laakmann McDowell",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 95f,
                            Title = "Cracking the Coding Interview"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Mark Lutz",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 130f,
                            Title = "Learning Python"
                        },
                        new
                        {
                            Id = 13,
                            Author = "David Flanagan",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 100f,
                            Title = "JavaScript: The Definitive Guide"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Douglas Crockford",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 75f,
                            Title = "JavaScript: The Good Parts"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Yukihiro Matsumoto",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 150f,
                            Title = "The Ruby Programming Language"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Joshua Bloch",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 120f,
                            Title = "Effective Java"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Herbert Schildt",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 90f,
                            Title = "Java: The Complete Reference"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Rich Hickey",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 140f,
                            Title = "Clojure for the Brave and True"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Kyle Simpson",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 100f,
                            Title = "You Don't Know JS"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Brian Kernighan",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 160f,
                            Title = "The C Programming Language"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Paul Barry",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 85f,
                            Title = "Head First Python"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Barry Burd",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 95f,
                            Title = "Java For Dummies"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Paul Deitel",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 105f,
                            Title = "Java How to Program"
                        },
                        new
                        {
                            Id = 24,
                            Author = "James Gosling",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 115f,
                            Title = "The Java Language Specification"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Patrick Chan",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 130f,
                            Title = "Java in a Nutshell"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Dean Wampler",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 100f,
                            Title = "Programming Scala"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Chris Pine",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 120f,
                            Title = "Learn to Program"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Luciano Ramalho",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 140f,
                            Title = "Fluent Python"
                        },
                        new
                        {
                            Id = 29,
                            Author = "David Thomas",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 150f,
                            Title = "Programming Elixir"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Robert Sedgewick",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 110f,
                            Title = "Algorithms"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Allen Downey",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 95f,
                            Title = "Think Python"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Shay Howe",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 105f,
                            Title = "Learn to Code HTML & CSS"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Ethan Brown",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 115f,
                            Title = "Learning JavaScript"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Marijn Haverbeke",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 125f,
                            Title = "Eloquent JavaScript"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Nicholas Zakas",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 90f,
                            Title = "Professional JavaScript for Web Developers"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Bjarne Stroustrup",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 100f,
                            Title = "The C++ Programming Language"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Scott Meyers",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 115f,
                            Title = "Effective C++"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Herbert Schildt",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 125f,
                            Title = "C++: The Complete Reference"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Stanley Lippman",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 135f,
                            Title = "C++ Primer"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Stephen Kochan",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 85f,
                            Title = "Programming in C"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Peter Van der Linden",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 95f,
                            Title = "Expert C Programming"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Tony Gaddis",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 105f,
                            Title = "Starting Out with C++"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Kathy Sierra",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 115f,
                            Title = "Head First Java"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Brett Slatkin",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 125f,
                            Title = "Effective Python"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Mark Pilgrim",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 135f,
                            Title = "Dive Into Python"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Zed Shaw",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 145f,
                            Title = "Learn Python the Hard Way"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Allen Downey",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 155f,
                            Title = "Think Java"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Thomas H. Cormen",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 165f,
                            Title = "Algorithms Unlocked"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Martin Kleppmann",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 175f,
                            Title = "Designing Data-Intensive Applications"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Sam Newman",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 185f,
                            Title = "Building Microservices"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Mary Shelley",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 95f,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Jules Verne",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 105f,
                            Title = "Journey to the Center of the Earth"
                        },
                        new
                        {
                            Id = 53,
                            Author = "H.G. Wells",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 115f,
                            Title = "The Time Machine"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Arthur Conan Doyle",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 125f,
                            Title = "The Lost World"
                        },
                        new
                        {
                            Id = 55,
                            Author = "George Orwell",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 135f,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Aldous Huxley",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 145f,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Ray Bradbury",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 155f,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Philip K. Dick",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 165f,
                            Title = "Do Androids Dream of Electric Sheep?"
                        },
                        new
                        {
                            Id = 59,
                            Author = "Isaac Asimov",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 175f,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 60,
                            Author = "Frank Herbert",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 185f,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 61,
                            Author = "J.R.R. Tolkien",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 95f,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 62,
                            Author = "J.K. Rowling",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 105f,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 63,
                            Author = "C.S. Lewis",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 115f,
                            Title = "The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Id = 64,
                            Author = "Suzanne Collins",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 125f,
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = 65,
                            Author = "Veronica Roth",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 135f,
                            Title = "Divergent"
                        },
                        new
                        {
                            Id = 66,
                            Author = "Rick Riordan",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 145f,
                            Title = "The Lightning Thief"
                        },
                        new
                        {
                            Id = 67,
                            Author = "George R.R. Martin",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 155f,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = 68,
                            Author = "Patrick Rothfuss",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 165f,
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = 69,
                            Author = "Brandon Sanderson",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 175f,
                            Title = "Mistborn"
                        },
                        new
                        {
                            Id = 70,
                            Author = "Robert Jordan",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 185f,
                            Title = "The Eye of the World"
                        },
                        new
                        {
                            Id = 71,
                            Author = "Leo Tolstoy",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 195f,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 72,
                            Author = "Fyodor Dostoevsky",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 205f,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 73,
                            Author = "Charles Dickens",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 215f,
                            Title = "Great Expectations"
                        },
                        new
                        {
                            Id = 74,
                            Author = "Jane Austen",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 225f,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 75,
                            Author = "Emily Bronte",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 235f,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 76,
                            Author = "Charlotte Bronte",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 245f,
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            Id = 77,
                            Author = "Mark Twain",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 255f,
                            Title = "Adventures of Huckleberry Finn"
                        },
                        new
                        {
                            Id = 78,
                            Author = "Ernest Hemingway",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 265f,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 79,
                            Author = "F. Scott Fitzgerald",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 275f,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 80,
                            Author = "John Steinbeck",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 285f,
                            Title = "Of Mice and Men"
                        },
                        new
                        {
                            Id = 81,
                            Author = "William Golding",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 295f,
                            Title = "Lord of the Flies"
                        },
                        new
                        {
                            Id = 82,
                            Author = "Harper Lee",
                            BookCategoryId = 6,
                            Ordered = false,
                            Price = 305f,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 83,
                            Author = "Toni Morrison",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 315f,
                            Title = "Beloved"
                        },
                        new
                        {
                            Id = 84,
                            Author = "Margaret Atwood",
                            BookCategoryId = 7,
                            Ordered = false,
                            Price = 325f,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = 85,
                            Author = "Khaled Hosseini",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 335f,
                            Title = "The Kite Runner"
                        },
                        new
                        {
                            Id = 86,
                            Author = "Markus Zusak",
                            BookCategoryId = 8,
                            Ordered = false,
                            Price = 345f,
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = 87,
                            Author = "Yann Martel",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 355f,
                            Title = "Life of Pi"
                        },
                        new
                        {
                            Id = 88,
                            Author = "Paulo Coelho",
                            BookCategoryId = 9,
                            Ordered = false,
                            Price = 365f,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 89,
                            Author = "Dan Brown",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 375f,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 90,
                            Author = "Stieg Larsson",
                            BookCategoryId = 10,
                            Ordered = false,
                            Price = 385f,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 91,
                            Author = "Gillian Flynn",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 395f,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 92,
                            Author = "Stephen King",
                            BookCategoryId = 1,
                            Ordered = false,
                            Price = 405f,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 93,
                            Author = "Dean Koontz",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 415f,
                            Title = "Watchers"
                        },
                        new
                        {
                            Id = 94,
                            Author = "Clive Barker",
                            BookCategoryId = 2,
                            Ordered = false,
                            Price = 425f,
                            Title = "The Hellbound Heart"
                        },
                        new
                        {
                            Id = 95,
                            Author = "Anne Rice",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 435f,
                            Title = "Interview with the Vampire"
                        },
                        new
                        {
                            Id = 96,
                            Author = "Bram Stoker",
                            BookCategoryId = 3,
                            Ordered = false,
                            Price = 445f,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 97,
                            Author = "Oscar Wilde",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 455f,
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            Id = 98,
                            Author = "H.P. Lovecraft",
                            BookCategoryId = 4,
                            Ordered = false,
                            Price = 465f,
                            Title = "At the Mountains of Madness"
                        },
                        new
                        {
                            Id = 99,
                            Author = "Edgar Allan Poe",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 475f,
                            Title = "The Complete Tales and Poems"
                        },
                        new
                        {
                            Id = 100,
                            Author = "Mary Shelley",
                            BookCategoryId = 5,
                            Ordered = false,
                            Price = 485f,
                            Title = "The Last Man"
                        });
                });

            modelBuilder.Entity("API.Entities.BookCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "computer",
                            SubCategory = "algorithm"
                        },
                        new
                        {
                            Id = 2,
                            Category = "computer",
                            SubCategory = "programming languages"
                        },
                        new
                        {
                            Id = 3,
                            Category = "computer",
                            SubCategory = "networking"
                        },
                        new
                        {
                            Id = 4,
                            Category = "computer",
                            SubCategory = "hardware"
                        },
                        new
                        {
                            Id = 5,
                            Category = "mechanical",
                            SubCategory = "machine"
                        },
                        new
                        {
                            Id = 6,
                            Category = "mechanical",
                            SubCategory = "transfer of energy"
                        },
                        new
                        {
                            Id = 7,
                            Category = "mathematics",
                            SubCategory = "calculus"
                        },
                        new
                        {
                            Id = 8,
                            Category = "mathematics",
                            SubCategory = "algebra"
                        });
                });

            modelBuilder.Entity("API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("FinePaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Returned")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountStatus = "ACTIVE",
                            CreatedOn = new DateTime(2023, 11, 1, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "",
                            MobileNumber = "1234567890",
                            Password = "admin1999",
                            UserType = "ADMIN"
                        });
                });

            modelBuilder.Entity("API.Entities.Book", b =>
                {
                    b.HasOne("API.Entities.BookCategory", "BookCategory")
                        .WithMany()
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("API.Entities.Order", b =>
                {
                    b.HasOne("API.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
